%{
#include "language.tab.h"
%}

%token SCOPE_BEGIN SCOPE_END
%token ARG_BEGIN ARG_END ARG_SEPARATOR
%token ARRAY_BEGIN ARRAY_END ARRAY_SEPARATOR
%token TYPE_LEAF TYPE_METHOD TYPE_SITE TYPE_BLOCK TYPE_STRUCT

%%
%%
